defaults: &defaults
  adapter: mysql2
  encoding: utf8
  reconnect: true
  pool: 5
  username: root
  password: 

development:
  <<: *defaults
  database: myapp_dev

test:
  <<: *defaults
  database:  myapp_test